admin:
  orders:
    create: true
    edit: true
    delete: true
  products:
    create: false
    edit: true
    delete: true  
manager:
  orders:
    create: true
    edit: true
    delete: false
  products:
    create: true
    edit: true
    delete: false
